### ISSUE TITLE
Intel dataset is broken

### ISSUE THREAD

**Issue by babaksit** [Ahmed-Fathalla/LSTM-DPS-for-IoT#1]
Hello,

Trying to unrar the Intel dataset, but getting the error, could you please fix it?

Thanks.

**Comment by Ahmed-Fathalla** [comment]
Thanks for your feedback,Dataset links are available at [LSTM-DPS-for-IoT/Intel-DS link.md at master · Ahmed-Fathalla/LSTM-DPS-for-IoT](https://github.com/Ahmed-Fathalla/LSTM-DPS-for-IoT/blob/master/data/Intel-DS%20link.md)

Original dataset: http://db.csail.mit.edu/labdata/labdata.html
Uncompressed version: https://drive.google.com/file/d/1zhS-Jdr9Y8kP5xy_hjzYmm5afTWkfS43/view?usp=sharing

**Comment by babaksit** [comment]
Thank you for your reply. Then I will close the issue :)
